<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ViewAllUsers.aspx.cs" Inherits="AdminAccess_ViewAllUsers" %>

<%@ Register Src="~/TemplateControls/UpdateProgressBar.ascx" TagPrefix="utmpl" TagName="UpdateProgressBar" %>


<asp:Content ID="Title" ContentPlaceHolderID="Title" runat="Server">
    Users
</asp:Content>

<asp:Content ID="Header" ContentPlaceHolderID="Header" runat="Server">
    Users List
</asp:Content>

<asp:Content ID="Content" ContentPlaceHolderID="Content" runat="Server">

    <form id="form1" runat="server">
        <asp:ScriptManager ID="UsersScriptManager" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="UsersUpdatePanel" runat="server">
            <ContentTemplate>
                <asp:GridView ID="AllUsersGridView" runat="server" CssClass="table table-bordered table-striped table-hover"
                    AutoGenerateColumns="false"
                    AutoGenerateDeleteButton="false" AutoGenerateEditButton="false"
                    OnRowCancelingEdit="AllUsersGridViewRowCancelingEdit"
                    OnRowDeleting="AllUsersGridViewRowDeleting" OnRowEditing="AllUsersGridViewRowEditing"
                    OnRowUpdating="AllUsersGridViewRowUpdating">

                    <Columns>
                        <asp:BoundField DataField="UserName" HeaderText="Username" ReadOnly="true"
                            HeaderStyle-Width="10%" ItemStyle-Width="10%" FooterStyle-Width="10%" />

                        <asp:BoundField DataField="Email" HeaderText="Email"
                            HeaderStyle-Width="30%" ItemStyle-Width="30%" FooterStyle-Width="30%" />

                        <asp:TemplateField HeaderText="Role"
                            HeaderStyle-Width="30%" ItemStyle-Width="30%" FooterStyle-Width="30%">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server"
                                    Text='<%# Roles.GetRolesForUser(Eval("UserName").ToString())[0] %>'>
                                </asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="RoleDropdownList" runat="server" Width="100%"
                                    SelectedValue='<%# Roles.GetRolesForUser(Eval("UserName").ToString())[0] %>'>
                                    <asp:ListItem Value="user">User</asp:ListItem>
                                    <asp:ListItem Value="admin">Admin</asp:ListItem>
                                </asp:DropDownList>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:BoundField DataField="LastActivityDate" HeaderText="Last Activity" ReadOnly="true" />

                        <asp:TemplateField HeaderText="Modify"
                            HeaderStyle-Width="10%" ItemStyle-Width="10%" FooterStyle-Width="10%" >
                            <ItemTemplate>
                                <p><asp:Button ID="Button1" runat="server" CssClass="btn btn-primary"
                                    CommandName="Edit" Text="Edit" Width="100%" /></p>
                                <p><asp:Button ID="Button2" runat="server" CssClass="btn btn-danger"
                                    CommandName="Delete" Text="Delete" Width="100%"
                                    OnClientClick="return confirm('Are you sure you want to delete this user?')" /></p>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <p><asp:Button ID="Button3" runat="server" CssClass="btn btn-primary"
                                    CommandName="Update" Text="Update" Width="100%" /></p>
                                <p><asp:Button ID="Button4" runat="server" CssClass="btn btn-primary"
                                    CommandName="Cancel" Text="Cancel" Width="100%" /></p>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                <div runat="server" id="ResultDiv">
                    <asp:Label ID="ResultLabel" runat="server" />
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
        <utmpl:UpdateProgressBar runat="server" ID="UpdateProgressBar" />
    </form>
    <asp:HyperLink CssClass="btn btn-large btn-primary glyphicon glyphicon-plus-sign"
            ID="HyperLink1" runat="server" NavigateUrl="/AdminAccess/Users/AddNewUser.aspx">
            Add New User</asp:HyperLink>
</asp:Content>
