<?xml version="1.0" encoding="utf-8"?><Database Name="WarehouseManagement" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TMTXT-PC\SQLEXPRESS;Initial Catalog=WarehouseManagement;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WarehouseManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_DO" Member="DOs" ThisKey="UserId" OtherKey="UserID" Type="DO" />
      <Association Name="aspnet_User_WE" Member="WEs" ThisKey="UserId" OtherKey="UserID" Type="WE" />
    </Type>
  </Table>
  <Table Name="dbo.DOS" Member="DOs">
    <Type Name="DO">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DO_DOSDetail" Member="DOSDetails" ThisKey="ID" OtherKey="DOSID" Type="DOSDetail" />
      <Association Name="aspnet_User_DO" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="Provider_DO" Member="Provider" ThisKey="ProviderID" OtherKey="ID" Type="Provider" IsForeignKey="true" />
      <Association Name="Warehouse_DO" Member="Warehouse" ThisKey="WarehouseID" OtherKey="ID" Type="Warehouse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOSDetail" Member="DOSDetails">
    <Type Name="DOSDetail">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DOSID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="DO_DOSDetail" Member="DO" ThisKey="DOSID" OtherKey="ID" Type="DO" IsForeignKey="true" />
      <Association Name="Product_DOSDetail" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CurrentBalance" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_DOSDetail" Member="DOSDetails" ThisKey="ID" OtherKey="ProductID" Type="DOSDetail" />
      <Association Name="Product_WESDetail" Member="WESDetails" ThisKey="ID" OtherKey="ProductID" Type="WESDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Provider" Member="Providers">
    <Type Name="Provider">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPersonEmail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Provider_DO" Member="DOs" ThisKey="ID" OtherKey="ProviderID" Type="DO" />
      <Association Name="Provider_WE" Member="WEs" ThisKey="ID" OtherKey="ProviderID" Type="WE" />
    </Type>
  </Table>
  <Table Name="dbo.Warehouse" Member="Warehouses">
    <Type Name="Warehouse">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Warehouse_DO" Member="DOs" ThisKey="ID" OtherKey="WarehouseID" Type="DO" />
      <Association Name="Warehouse_WE" Member="WEs" ThisKey="ID" OtherKey="WarehouseID" Type="WE" />
    </Type>
  </Table>
  <Table Name="dbo.WES" Member="WEs">
    <Type Name="WE">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="WarehouseID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProviderID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="WE_WESDetail" Member="WESDetails" ThisKey="ID" OtherKey="WESID" Type="WESDetail" />
      <Association Name="Provider_WE" Member="Provider" ThisKey="ProviderID" OtherKey="ID" Type="Provider" IsForeignKey="true" />
      <Association Name="Warehouse_WE" Member="Warehouse" ThisKey="WarehouseID" OtherKey="ID" Type="Warehouse" IsForeignKey="true" />
      <Association Name="aspnet_User_WE" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WESDetail" Member="WESDetails">
    <Type Name="WESDetail">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WESID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Product_WESDetail" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="WE_WESDetail" Member="WE" ThisKey="WESID" OtherKey="ID" Type="WE" IsForeignKey="true" />
    </Type>
  </Table>
</Database>