<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ViewAllUsers.aspx.cs" Inherits="AdminAccess_ViewAllUsers" %>

<asp:Content ID="Title" ContentPlaceHolderID="Title" runat="Server">
    Users
</asp:Content>
<asp:Content ID="Content" ContentPlaceHolderID="Content" runat="Server">

    <form id="form1" runat="server">

        <asp:GridView ID="AllUsersGridView" runat="server" CssClass="Gridview" AutoGenerateColumns="false"
            AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
            OnRowCancelingEdit="AllUsersGridViewRowCancelingEdit"
            OnRowDeleting="AllUsersGridViewRowDeleting" OnRowEditing="AllUsersGridViewRowEditing"
            OnRowUpdating="AllUsersGridViewRowUpdating">
            <HeaderStyle BackColor="#df5015" />
            <Columns>
                <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="true" />
                <asp:BoundField DataField="Email" HeaderText="Email" />
            </Columns>
        </asp:GridView>
         <asp:Label ID="lblResult" runat="server" Font-Bold="true"/>
    </form>

</asp:Content>

