<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ViewAllUsers.aspx.cs" Inherits="AdminAccess_ViewAllUsers" %>

<asp:Content ID="Title" ContentPlaceHolderID="Title" runat="Server">
    Users
</asp:Content>
<asp:Content ID="Content" ContentPlaceHolderID="Content" runat="Server">

    <form id="form1" runat="server">

        <asp:GridView ID="AllUsersGridView" runat="server" CssClass="gridview table table-bordered table-striped table-hover"
            AutoGenerateColumns="false"
            AutoGenerateDeleteButton="false" AutoGenerateEditButton="false"
            OnRowCancelingEdit="AllUsersGridViewRowCancelingEdit"
            OnRowDeleting="AllUsersGridViewRowDeleting" OnRowEditing="AllUsersGridViewRowEditing"
            OnRowUpdating="AllUsersGridViewRowUpdating">

            <Columns>
                <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="true" />
                <asp:BoundField DataField="Email" HeaderText="Email" />
                <asp:BoundField DataField="LastActivityDate" HeaderText="Last Activity" ReadOnly="true" />

                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Button runat="server" CssClass="btn btn-primary" CommandName="Edit" Text="Edit" />
                        <asp:Button runat="server" CssClass="btn btn-primary" CommandName="Delete" Text="Delete" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:Button runat="server" CssClass="btn btn-primary" CommandName="Update" Text="Update" />
                        <asp:Button runat="server" CssClass="btn btn-primary" CommandName="Cancel" Text="Cancel" />
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <div runat="server" id="ResultDiv">
            <asp:Label ID="ResultLabel" runat="server" />
        </div>

    </form>

</asp:Content>

